export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS'; 
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const SWEETS_LOADING = 'SWEETS_LOADING';
export const SWEETS_FAILED = 'SWEETS_FAILED';
export const ADD_SWEETS = 'ADD_SWEETS';